-- Prerequisite: transaction prefix master table (dumped from live DB)
-- Generated by scripts/dump-t-prefix-sql.js
--
-- MySQL / MariaDB

CREATE TABLE IF NOT EXISTS t_prefix (
  uid INT NOT NULL AUTO_INCREMENT,
  prefix VARCHAR(10) NOT NULL,
  prefix_ref VARCHAR(10) NOT NULL,
  `desc` VARCHAR(255) NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 1,
  create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modify_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (uid),
  UNIQUE KEY uq_t_prefix_prefix (prefix),
  UNIQUE KEY uq_t_prefix_prefix_ref (prefix_ref)
);

INSERT INTO t_prefix (prefix, prefix_ref, `desc`, status)
VALUES
  ('ADJ', '_AD', 'Adjustment', 1),
  ('DN', '_DN', 'Delivery Note', 1),
  ('GRN', '_GR', 'Good Receive Note', 1),
  ('INV', '_INV', 'Invoices ', 1),
  ('PO', '_PO', 'Purchase Order', 1),
  ('QTA', '_QT', 'Quotation', 1),
  ('SO', '_SO', 'Sales Order', 1),
  ('ST', '_ST', 'Stocktake', 1)
ON DUPLICATE KEY UPDATE
  prefix_ref = VALUES(prefix_ref),
  `desc` = VALUES(`desc`),
  status = VALUES(status);
